bbs/urls.py
# -*- coding: utf-8 -*-
__author__ = 'puras'

from django.conf.urls import patterns, url
from bbs import views

urlpatterns = patterns('', 
    url(r'^$', views.index, name='index'),
    url(r'^node/(?P<node_id>\d+)/$', views.node, name='node'),
    url(r'^node/(?P<node_id>\d+)/topic/new/$', views.topic_create, name='topic_create'),
    url(r'^topic/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^topic/(?P<topic_id>\d+)/reply/$', views.topic_reply, name='topic_reply'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^join/$', views.join, name='join'),
    url(r'^password/$', views.change_password, name='password'),
)

moobo/urls.py
# -*- coding: utf-8 -*-
__author__ = 'puras'
from django.conf.urls import patterns, include, url
from django.views.static import serve
from django.conf import settings

from bbs.views import index

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'moobo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', index, name='bbs'),
    url(r'^bbs/', include('bbs.urls', namespace='bbs')),
    url(r'^upload/', include('editor.urls', namespace='editor')),
    url(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT
        }),
    # url(r'^blog/$', include(blog.urls, namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
)

bbs/models.py
# -*- coding: utf-8 -*-
__author__ = 'puras'
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='名称')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = '分类'

    def __unicode__(self):
        return self.name

class Node(models.Model):
    name = models.CharField(max_length=100, verbose_name='名称')
    category = models.ForeignKey(Category)

    class Meta:
        verbose_name = '节点'
        verbose_name_plural = '节点'

    def __unicode__(self):
        return self.name

class Topic(models.Model):
    title = models.CharField(max_length=1024, verbose_name='标题')
    content = models.TextField('内容')
    author = models.ForeignKey(User)
    node = models.ForeignKey(Node)
    category = models.ForeignKey(Category)
    pub_date = models.DateTimeField('发布时间')

    class Meta:
        verbose_name = '主题'
        verbose_name_plural = '主题'

    def __unicode__(self):
        return self.title

    def last_reply(self):
        reply = self.reply_set.all().order_by('-pub_date')[:1]
        if reply:
            return reply[0]
        else:
            return None

    def reply_count(self):
        return len(self.reply_set.all())

class Reply(models.Model):
    content = models.TextField('内容')
    topic = models.ForeignKey(Topic)
    author = models.ForeignKey(User)
    pub_date = models.DateTimeField('发布时间')

    class Meta:
        verbose_name = '回复'
        verbose_name_plural = '回复'

    def __unicode__(self):
        return self.content

bbs/forms.py
# -*- coding: utf-8 -*-
__author__ = 'puras'

from django import forms
from editor.kindeditor.widgets import KindEditor

class TopicForm(forms.Form):
    title = forms.CharField(widget = forms.TextInput(attrs={'size': '90', 'placeholder': '主题标题'}))
    # content = forms.CharField(widget=forms.Textarea(attrs={'cols': '90', 'rows': '20', 'placeholder': '主题内容'}))
    content = forms.CharField(widget=KindEditor(attrs={'cols': '90', 'rows': '20', 'placeholder': '主题内容'}))

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title.strip()) < 4:
            raise forms.ValidationError('内容过短')
        return title

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content.strip()) < 4:
            raise forms.ValidationError('内容过短')
        return content

class ReplyForm(forms.Form):
    # content = forms.CharField(widget=forms.Textarea(attrs={'cols': '90', 'rows': '10', 'placeholder': '回复内容'}))
    content = forms.CharField(widget=KindEditor(attrs={'class': 'form-control highlight', 'rows': '3', 'placeholder': '回复内容'}))

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content.strip()) < 4:
            raise forms.ValidationError('内容过短')
        return content

bbs/views.py
# -*- coding: utf-8 -*-
__author__ = 'puras'

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from django import forms
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm

from datetime import datetime

from bbs.models import Topic, Node, Category, Reply
from bbs.forms import TopicForm, ReplyForm

# Create your views here.
def index(req):
    lastest_topic_list = Topic.objects.order_by('-pub_date')[:20]
    category_list = Category.objects.all()
    return render(req, 'index.html', {
        'lastest_topic_list': lastest_topic_list,
        'category_list': category_list,
        })

def topic(req, topic_id):
    topic = get_object_or_404(Topic, pk = topic_id)
    reply_form = ReplyForm()
    return render(req, 'topic.html', {'topic': topic, 'reply_form': reply_form})

def topic_create(req, node_id):
    node = get_object_or_404(Node, pk = node_id)
    if req.method == 'POST':
        form = TopicForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            tp = Topic.objects.create(
                title = cd['title'],
                content = cd['content'],
                author = req.user,
                category = node.category,
                node = node,
                pub_date = datetime.now(),
            )
            tp.save()
            return HttpResponseRedirect(reverse('bbs:topic', args = (tp.id, )))
    else:
        form = TopicForm()

    return render(req, 'topic/create.html', {'form': form })

def topic_reply(req, topic_id):
    topic = get_object_or_404(Topic, pk = topic_id)
    if req.method == 'POST':
        form = ReplyForm(req.POST)
        if form.is_valid():
            cd = form.cleaned_data
            re = Reply.objects.create(
                content = cd['content'],
                topic = topic,
                author = req.user,
                pub_date = datetime.now(),
            )
            re.save()
            return HttpResponseRedirect(reverse('bbs:topic', args = (topic_id, )))
        else:
            return render(req, 'topic.html', {'topic': topic, 'reply_form': form})


def node(req, node_id):
    node = get_object_or_404(Node, pk = node_id)
    topic_list = Topic.objects.order_by('-pub_date').filter(node_id = node_id)[:20]
    return render(req, 'node.html', { 
        'node': node,
        'topic_list': topic_list
    })

def login(req):
    if req.method == 'POST':
        username = req.POST.get('username', '')
        passwd = req.POST.get('passwd', '')
        user = auth.authenticate(username = username, password = passwd)
        if user is not None and user.is_active:
            auth.login(req, user)
            return HttpResponseRedirect('/')
        else:
            return render(req, 'login.html')

    return render(req, 'login.html')

def logout(req):
    auth.logout(req)
    return HttpResponseRedirect(reverse('bbs:login'))

def join(req):
    if req.method == 'POST':
        form = UserCreationForm(req.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
        return render(req, 'join.html', { 'form': form, })

def change_password(req):
    if req.method == 'POST':
        old_passwd = req.POST.get('old_passwd', '')
        passwd = req.POST.get('passwd', '')
        repasswd = req.POST.get('repasswd', '')
        if not passwd == repasswd:
            # 传递错误信息,新密码与确认新密码不同
            return render(req, 'password.html', { 'error': None })
        user = req.user
        test_user = auth.authenticate(username = user.username, password = old_passwd)
        if test_user is not None:
            user.set_password(passwd)
            user.save()
            return logout(req)
        else:
            # 传递错误信息，原密码不符
            return render(req, 'password.html')

    else:
        return render(req, 'password.html')

bbs/templates/base.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block body %}
<!-- container ================================================== -->
<div class="container bs-docs-container content">
    <div class="row"> 
        <div class="col-md-9" role="main">
            {% block content %}
            {% endblock %}
        </div>
        <div class="col-md-3">
            <div class="box highlight">
                <div class="cell"> 
                    {% if user.is_authenticated %}
                    <a href="#" class="user" style="max-height:48px; max-width:48px;"></a>
                    <h4><a href="#" class="user_name">{{ user.username }}</a></h4>
                    {% else %}
                    <div class="tab_title"> <a href="javascript:void(0)">MooBo</a></div>
                    <a href="{% url 'bbs:login' %}">登录</a> | <a href="{% url 'bbs:join' %}">注册</a>
                    {% endif %}
                <!-- <a href="#" class="user" style="max-height:48px; max-width:48px;"></a>
                <h4><a href="#" class="user_name">602516883</a></h4>
                <div class="main">
                    <p class="dark"> <span class="bigger">0</span> <span>节点收藏</span> </p>
                    <p class="dark"> <span class="bigger">0</span> <span>主题收藏</span> </p>
                    <p class="dark"> <span class="bigger">0</span> <span>特别关注</span> </p>
                </div> -->
                </div>
                <div class="inner">
                <!-- <div id="money" class="fr"> <a class="balance_area" href="#"> 0 <span></span></a> </div> -->
                    <a href="#" style="line-height:30px">0 条未读提醒</a> 
                </div>
            </div>

            <div class="box">
                <div class="inner tab_title"> <a href="/?tab=tech">最近热议主题</a></div>
                <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
                <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
                <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bbs/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}

<div class="box highlight">
    <div class="inner tab_title"> <a href="javascript:void(0);">最新主题</a></div>
    {% if lastest_topic_list %}
        {% for topic in lastest_topic_list %}
            <div class="cell item"> 
                <span class="user"></span>
                <h5><a href="{% url 'bbs:topic' topic.id %}">{{topic.title}}</a></h5>
                <div class="info">
                    <a class="node" href="{% url 'bbs:node' topic.node.id %}">{{topic.node.name}}</a>
                    <strong><a href="#">{{topic.author.username}}</a></strong> {{topic.pub_date}} 
                    最后回复来自
                    <strong><a href="#">{{topic.last_reply.author.username}}</a></strong>.
                </div>
                <a class="count_livid" href="javascript:void(0);">{{topic.reply_count}}</a>
            </div>
        {% endfor %}
    {% endif %}
</div>
<div class="box">
    <div class="inner tab_title"> <a href="#">节点导航</a><!-- <a href="#" class="text-right">浏览全部节点</a> --></div>
    {% if category_list %}
        {% for cate in category_list %}
            <div class="cell item">
                <p class="node-title">{{cate.name}}</p>
                <div class="node-item"> 
                 {% if cate.node_set.all %}
                    {% for node in cate.node_set.all %}
                    <a href="{% url 'bbs:node' node.id %}">{{node.name}}</a>
                    {% endfor %}
                {% endif %}
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

bbs/templates/join.html
{% extends 'layout.html' %}

{% block body %}
<div class="container content">
    <div class="row"> 
      <div class="col-md-9" role="main">
        <div class="box highlight">
          <div class="inner tab_title highlight"> <a href="#">MooBo </a>><a href="{% url 'bbs:join' %}"> 注册</a></div>
          <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
              <div class="col-sm-3">
                <!-- <input type="email" class="form-control" id="inputEmail3" placeholder="Email" > -->
                {{form.username}}
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
              <div class="col-sm-3">
                <!-- <input type="password" class="form-control" id="inputPassword3" placeholder="Password"> -->
                {{form.password1}}
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">确认密码</label>
              <div class="col-sm-3">
                <!-- <input type="password" class="form-control" id="inputPassword3" placeholder="Password"> -->
                {{form.password2}}
              </div>
            </div>
            <!-- <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                  <label>
                    <input type="checkbox">
                    Remember me </label>
                </div>
              </div>
            </div> -->
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">注册</button>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box highlight">
          <div class="cell"> <strong>这是一个关于技术分享和探索的地方</strong> </div>
          <div class="inner">
            已有账号 : <button type="button" class="btn btn-primary" onclick="location.href='{% url 'bbs:login' %}';">直接->登录</button>
          </div>
        </div>
        <div class="box">
          <div class="inner tab_title"> <a href="/?tab=tech">最近热议主题</a></div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bbs/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="IE=edge" http-equiv="X-UA-Compatible">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="" name="description">
        <meta content="" name="author">
        <title>MooBo-我们自己的论坛</title>
        {% load staticfiles %}
        {% load moobo_tags %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/lib/bootstrap.css' %}">

        <!-- Optional theme -->
        <link rel="stylesheet" href="{% static 'css/lib/bootstrap-theme.css' %}">

        <!-- style CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />

        <link href="{% static 'editor/kindeditor-4.1.9/themes/default/default.css' %}" type="text/css" media="all" rel="stylesheet" />
        <link href="{% static 'editor/kindeditor-4.1.9/plugins/code/prettify.css' %}" type="text/css" media="all" rel="stylesheet" />

        
        <!-- Latest compiled and minified JavaScript --> 
        <script src="{% static 'js/lib/jquery-1.10.2.min.js' %}"></script> 
        <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'editor/kindeditor-4.1.9/kindeditor.js' %}"></script>
        <script type="text/javascript" src="{% static 'editor/kindeditor-4.1.9/plugins/code/prettify.js' %}"></script>
        <script type="text/javascript" src="{% static 'editor/kindeditor_init.js' %}"></script>
    </head>
    <body>
    <header class="navbar navbar-fixed-top bs-docs-nav navbar-inner" role="banner">
        <div class="container">
            <div class="navbar-header"> <a href="{% url 'bbs' %}" class="navbar-brand"><span>MOOBO</span> </a></div>
            <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'bbs' %}">首页</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="javascript:void(0);">欢迎您， {{ user.username }}</a></li>
                    <li><a href="{% url 'bbs:password' %}">修改密码</a></li>
                    <li><a href="{% url 'bbs:logout' %}">注销</a></li>
                    {% else %}
                    <li><a href="{% url 'bbs:login' %}">登录</a></li>
                    <li><a href="{% url 'bbs:join' %}">注册</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <div id="wrap"> 
        {% block body %}
        {% endblock %}

        <div id="push"></div>
    </div>
    <div id="footer">
        <div class="container">
            <p class="muted credit"> 本论坛使用Python开发,使用django框架,前端页面样式使用bootstrap</p>
            <p class="muted credit">程序开发: <a href="#">Parus.He</a> | 页面开发: <a href="#">张雪</a></p>
        </div>
    </div>
    </body>
</html>

bbs/templates/login.html
{% extends 'layout.html' %}

{% block body %}
<div class="container content">
    <div class="row"> 
      <div class="col-md-9" role="main">
        <div class="box highlight">
          <div class="inner tab_title highlight"> <a href="#">MooBo </a>><a href="{% url 'bbs:login' %}"> 登录</a></div>
          <form class="form-horizontal" role="form" action="" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="inputEmail3" class="col-sm-2 control-label">用户名</label>
              <div class="col-sm-3">
                <input type="text" class="form-control" id="username" name="username" placeholder="username" >
              </div>
            </div>
            <div class="form-group">
              <label for="inputPassword3" class="col-sm-2 control-label">密码</label>
              <div class="col-sm-3">
                <input type="password" class="form-control" id="passwd" name="passwd" placeholder="Password" value="">
              </div>
            </div>
            <!-- <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                  <label>
                    <input type="checkbox">
                    Remember me </label>
                </div>
              </div>
            </div> -->
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">登录</button>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-3">
        <div class="box highlight">
          <div class="cell"> <strong>这是一个关于技术分享和探索的地方</strong> </div>
          <div class="inner">
            没有账号 : <button type="button" class="btn btn-primary" onclick="location.href='{% url 'bbs:join' %}';">注册</button>
          </div>
        </div>
        <div class="box">
          <div class="inner tab_title"> <a href="/?tab=tech">最近热议主题</a></div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
          <div class="cell"> <a class="user" href="#" style="max-height:24px; max-width:24px"></a><a href="/t/89617">windows下你必定会用到的快捷键?</a> </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

bbs/templates/node.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<div class="box highlight">
    <div class="inner tab_title"><a href="{% url 'bbs' %}">MOOBO</a> &gt; <a href="javascript:void(0)">{{node.name}}</a></div>
    {% if user.is_authenticated %}
    <a href="{% url 'bbs:topic_create' node.id %}">发布主题</a>
    {% endif %}

    {% if topic_list %}
        {% for topic in topic_list %}
            <div class="cell item"> 
                <span class="user"></span>
                <h5><a href="{% url 'bbs:topic' topic.id %}">{{topic.title}}</a></h5>
                <div class="info">
                    <a class="node" href="{% url 'bbs:node' topic.node.id %}">{{topic.node.name}}</a>
                    <strong><a href="#">{{topic.author.username}}</a></strong> {{topic.pub_date}}  最后回复来自
                    <strong><a href="#">{{topic.last_reply.author.username}}</a></strong>.
                </div>
                <a class="count_livid" href="javascript:void(0);">{{topic.reply_count}}</a>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

bbs/templates/password.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<div class="box-title">最新主题</div>
<form action="" method="post">
{% csrf_token %}
<table>
    <tbody>
        <tr>
            <td>原密码</td>
            <td><input type="password" id="old_passwd" name="old_passwd" value="" /></td>
        </tr>
        <tr>
            <td>新密码</td>
            <td><input type="password" id="passwd" name="passwd" value="" /></td>
        </tr>
        <tr>
            <td>确认新密码</td>
            <td><input type="password" id="repasswd" name="repasswd" value="" /></td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" />
            </td>
        </tr>
    </tbody>
</table>
</form>
{% endblock %}

bbs/templates/topic.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load moobo_tags %}

{% block content %}
<div class="box highlight">
    <div class="inner tab_title"> <a href="{% url 'bbs' %}">MOOBO</a> > <a href="{% url 'bbs:node' topic.node.id %}">{{ topic.node.name }}</a></div>
    <div class="content_title"> 
        <a href="#" class="user fr"></a>
        <h3>{{topic.title}}</h3>
        <small class="gray"> By <a href="javascript:void(0);">{{topic.author.username}}</a> · {{topic.pub_date}} · <!-- 1752 次点击 --> </small> 
    </div>
    <div class="cell">
        <div class="topic_content"> 
            {{topic.content|md}}
        </div>
    </div>
</div>
<div class="box highlight">
    <div class="inner tab_title"> <span class="gray"> {{topic.reply_count}} 回复 <!-- <strong class="snow">|</strong> 直到 2013-11-21 14:35:49 --> </span></div>
    {% if topic.reply_set.all %}
        {% for reply in topic.reply_set.all %}
          <div class="cell" id="reply_{{forloop.counter}}"> <a href="#" class="user"></a>
            <div class="fr"> <a href="#" class="reply_img" onclick="return reply_to('{{reply.author.username}}');" title="回复该层"></a> <!-- <span class="no">1</span> --> </div>
            <strong> <a class="dark" href="javascript:void(0);">{{reply.author.username}}</a> </strong> 
            <span class="small gray">{{reply.pub_date}}</span> <!-- <span class="small">♥ 2</span> -->
            <div class="sep5"></div>
            <div class="reply_content">
                {{reply.content|md}}
            </div>
          </div>
        {% endfor %}
    {% endif %}
</div>
<div class="box ">
    <div class="inner tab_title"> 添加一条新回复<a href="#" class="fr">回到顶部</a></div>
    {% if user.is_authenticated %}
        {% if reply_form.errors %}
            {{ reply_form.errors }}
        {% endif %}
        <form action="{% url 'bbs:topic_reply' topic.id %}" method="POST">
        <div class="cell item">
            {% csrf_token %}
            {{ reply_form.content }}
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
        </form>
    {% else %}
        <h4>请先<a href="{% url 'bbs:login' %}">登录</a>或<a href="{% url 'bbs:join' %}">注册</a>后再进行回复</h4>
    {% endif %}
</div>
<script type="text/javascript">
    function reply_to(username) {
        kindeditor.insertHtml('@' + username + '  <br />');
        return false;
    }
</script>
{% endblock %}